language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy bienvenuparfait/reverseproxy:v1
  - docker tag udagram-api-user bienvenuparfait/udagram-api-user:v1
  - docker tag udagram-api-feed bienvenuparfait/udagram-api-feed:v1 
  - docker tag udagram-frontend bienvenuparfait/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bienvenuparfait/reverseproxy
  - docker push bienvenuparfait/udagram-api-user
  - docker push bienvenuparfait/udagram-api-feed
  - docker push bienvenuparfait/udagram-frontend

